### ISSUE TITLE
什「麼」的注音輸入方式

### ISSUE THREAD

**Issue by Zaction12** [chewing/libchewing-data#22]
不知有沒有人反應或建議過，現在新酷音要輸入「什麼」的「麼」必須打ㄇㄚ．，而非ㄇㄛ．。
以台灣的注音輸入習慣，應該是ㄇㄛ．，例如微軟新注音或自然輸入法都是這樣，
個人建議新酷音在注音輸入的部份是否還是能循大多數人的使用習慣去設定？
謝謝。

**Comment by kidwm** [comment]
https://www.moedict.tw/%E9%BA%BC

**Comment by Zaction12** [comment]
謝謝！

2017-05-23 11:27 GMT+08:00 Chen-Heng Chang <notifications@github.com>:
