### ISSUE TITLE
怎麼的麼 建議新增輸入方式

### ISSUE THREAD

**Issue by GelionLin** [chewing/libchewing-data#23]
在微軟新注音、奇摩輸入法、或是其他注音輸入法中
怎麼的麼 輸入為ㄇㄛ˙
但在酷音中無法這樣輸入
需要改為ㄇㄚˊ
這部份與多數注音輸入法不同, 建議可以新增一組輸入方式
感謝

**Comment by kidwm** [comment]
https://www.moedict.tw/%E9%BA%BC
