### ISSUE TITLE
注音

### ISSUE THREAD

**Issue by Quentice** [chewing/libchewing-data#8]
這『麼』、那『麼』的注音拼法

ㄇㄛ˙卻完全打不出來

**Comment by kidwm** [comment]
「˙ㄇㄜ」
惡靈退散。

**Comment by Quentice** [comment]
啊 你不就很了不起？？！ 隨便就跟說別人說惡靈退散？！  就算我從小就用錯注音也不干你的事吧！

2015-07-29 9:50 GMT+08:00 Chen-Heng Chang <notifications@github.com>:

**Comment by wi1d5ky** [comment]
https://github.com/chewing/libchewing-data/issues?q=is%3Aissue+is%3Aclosed
@Quentice 你看看這個 link...
